@host = http://localhost:8888

GET {{host}}/api/v1/actor-types
Content-Type: application/json
Accept: application/json

###

GET {{host}}/api/v1/actor-types/7bc5a48f0-92a7-495e-8ca1-54ed335d5fa4
Content-Type: application/json
Accept: application/json