version: "3.4"

services:
    auditbase_receiver:
        container_name: auditbase_receiver
        build:
            context: .
            dockerfile: docker/dev/receiver.Dockerfile
        depends_on: 
            - auditbase_db
            - auditbase_rabbit
        ports:
            - "8888:3001"

    auditbase_backoffice:
        container_name: auditbase_backoffice
        build:
            context: .
            dockerfile: docker/dev/backoffice.Dockerfile
        depends_on:
            - auditbase_db
            - auditbase_rabbit
        ports:
            - "8889:3000"

    auditbase_consumer:
        container_name: auditbase_consumer
        build:
            context: .
            dockerfile: docker/dev/consumer.Dockerfile
        depends_on: 
            - auditbase_db
            - auditbase_rabbit

    auditbase_errors_consumer:
        container_name: auditbase_errors_consumer
        build:
            context: .
            dockerfile: docker/dev/errors-consumer.Dockerfile
        depends_on: 
            - auditbase_db
            - auditbase_rabbit

    auditbase_redis:
        container_name: auditbase_redis
        image: redis:5-alpine
        env_file:
            - ./.env
        ports:
            - 63799:6379
        restart: always
        tty: true

    auditbase_rabbit:
        hostname: auditbase_rabbit
        image: rabbitmq:3-management-alpine
        container_name: auditbase_rabbit
        volumes:
            - auditbase_rabbit_volume:/var/lib/rabbitmq
        ports: 
            - 15672:15672
        env_file:
            - ./.env

    auditbase_db:
        image: mysql:8.0
        container_name: auditbase_db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: auditbase
            MYSQL_USER: auditbase
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"

volumes:
    auditbase_rabbit_volume:
    auditbase_db_volume:
        
            