GET {{back-office}}/api/v1/entities
Accept: application/json
Cache-Control: no-cache

###

GET {{back-office}}/api/v1/entities/ea0d5abe-8489-4a54-bacf-e4ea6d58c964
Accept: application/json
Cache-Control: no-cache

