GET http://localhost:8888/api/v1/events
Content-Type: application/json

###

GET http://localhost:8888/api/v1/events/897fe984-4445-43b0-9c71-797da1da242b
Content-Type: application/json

###

POST http://localhost:8888/api/v1/events
Content-Type: application/json

{
    "targetId": "121289123",
	"targetType": {
		"name": "subscription"
	},
	"targetService": {
		"name": "billing"
	},
	"actorId": "749212201",
	"actorType": {
		"name": "user"
	},
	"actorService": {
		"name": "front-end"
	},
    "eventName": "transactionActivated",
    "emittedAt": 1578176012,
	"delta": {
		"status": [null, "ACTIVATED"]
	}
}