GET http://localhost:8888/api/v1/events
Content-Type: application/json

###

GET http://localhost:8888/api/v1/events/897fe984-4445-43b0-9c71-797da1da242b
Content-Type: application/json

###

GET http://localhost:8888/api/v1/events/count
Content-Type: application/json

###

GET http://localhost:8888/api/v1/events/queue
Content-Type: application/json

###

POST http://localhost:8888/api/v1/events
Content-Type: application/json

{
    "targetId": "9999995",
	"targetType": {
		"name": "article"
	},
	"targetService": {
		"name": "article-storage"
	},
	"actorId": "0000009",
	"actorType": {
		"name": "actor"
	},
	"actorService": {
		"name": "back-office"
	},
    "eventName": "articlePublished",
    "emittedAt": 1578173213,
	"delta": {
		"status": ["PUBLISHED", "DEPUBLISHED"]
	}
}

###

POST http://localhost:8888/api/v1/events
Content-Type: application/json

{
	"id": "64e1d8fb-b065-436d-afd0-5fbcb752a4e2",
    "targetId": "12345",
	"targetType": {
		"name": "subscription"
	},
	"targetService": {
		"name": "billing"
	},
	"actorId": "999999",
	"actorType": {
		"name": "promoter"
	},
	"actorService": {
		"name": "backoffice"
	},
    "eventName": "subscriptionAcquired",
    "emittedAt": 1578173212,
	"delta": {
		"status": [null, "ACTIVATED"]
	}
}