@host = http://localhost:8888

GET {{host}}/api/v1/microservices

###

POST {{host}}/api/v1/microservices HTTP/1.1
content-type: application/json

{
    "name": "nessie",
    "description": "Nessie serv"
}

###

PUT {{host}}/api/v1/microservices/35e46ed5-fe56-4445-878e-9c32ae54bfd0
content-type: application/json

{
    "name": "FOO-2",
    "description": "Baaaaaaaaar"
}
