POST {{receiver}}/api/v1/events
Content-Type: application/json
Accept: application/json

{
    "targetId": "9309213",
	"targetEntity": "article",
	"targetService": "article-storage",
    "parentEventId": null,
	"actorId": "9",
    "crud": "create",
	"actorEntity": "promoter",
	"actorService": "back-office",
    "eventName": "articlePublished",
    "emittedAt": 1578174512,
	"changes": [
      {
        "propertyName": "status",
        "from": null,
        "to": "published"
      },
      {
        "propertyName": "value",
        "from": "bar",
        "to": "baz"
      }
	]
}

###

POST {{receiver}}/api/v1/events
Content-Type: application/json
Accept: application/json

{
	"id": "34e1d82a-a065-436d-afd0-5fbcb752a4e1",
    "targetId": "122242120",
	"targetEntity": "subscription",
	"targetService": "billing",
    "crud": "update",
	"actorId": "88999",
	"actorEntity": "user",
	"actorService": "front",
    "eventName": "subscriptionUpdated",
    "emittedAt": 1578173212,
  "changes": [
    {
      "propertyName": "account_status",
      "from": "foo",
      "to": "1234"
    },
    {
      "propertyName": "meta",
      "from": "baz",
      "to": null
    },
    {
      "propertyName": "balance",
      "from": 12345.876,
      "to": 16345.876
    },
    {
      "propertyName": "complaints",
      "from": "5",
      "to": "6"
    }
  ]
}

###

POST {{receiver}}/api/v1/events
Content-Type: application/json
Accept: application/json

{
  "targetId": "111",
  "targetEntity": "post",
  "targetService": "post-service",
  "parentEventId": null,
  "actorId": "999",
  "crud": "create",
  "actorEntity": "blogger",
  "actorService": "blogger-hub",
  "eventName": "blogPostCreated",
  "emittedAt": 1578174655,
  "changes": [
    {
      "propertyName": "text",
      "currentPropertyType": "string",
      "from": null,
      "to": "foo says bar"
    },
    {
      "propertyName": "title",
      "currentPropertyType": "string",
      "from": null,
      "to": "baz title"
    },
    {
      "propertyName": "rating",
      "currentPropertyType": "float",
      "from": null,
      "to": 1.1
    },
    {
      "propertyName": "views",
      "currentPropertyType": "integer",
      "from": null,
      "to": 1
    }
  ]
}

###

POST {{receiver}}/api/v1/events
Content-Type: application/json
Accept: application/json

{
  "targetId": "111",
  "targetEntity": "post",
  "targetService": "post-service",
  "parentEventId": null,
  "actorId": "999",
  "crud": "delete",
  "actorEntity": "blogger",
  "actorService": "blogger-hub",
  "eventName": "blogPostDeleted",
  "emittedAt": 1578174657,
  "changes": [
    {
      "propertyName": "text",
      "from": "foo says bar",
      "to": null
    },
    {
      "propertyName": "title",
      "from": "baz title",
      "to": null
    },
    {
      "propertyName": "rating",
      "from": 1,
      "to": null
    }
  ]
}