POST {{receiver}}/api/v1/events
Content-Type: application/json
Accept: application/json

{
    "targetId": "9309213",
	"targetEntity": "article",
	"targetService": "article-storage",
	"actorId": "0000009",
	"actorEntity": "promoter2",
	"actorService": "back-office",
    "eventName": "articlePublished",
	"changes": [
      {
        "propertyName": "status2",
        "currentPropertyType": "string",
        "from": null,
        "to": "baz"
      },
      {
        "propertyName": "value",
        "currentPropertyType": "string",
        "from": "bar",
        "to": "baz"
      }
	]
}

###

POST {{receiver}}/api/v1/events
Content-Type: application/json
Accept: application/json

{
	"id": "34e1d82a-a065-436d-afd0-5fbcb752a4e1",
    "targetId": "122242120",
	"targetEntity": "subscription",
	"targetService": "billing",
	"actorId": "88999",
	"actorEntity": "user",
	"actorService": "front",
    "eventName": "subscriptionCanceled",
    "emittedAt": 1578173212,
  "changes": [
    {
      "propertyName": "status_10",
      "currentPropertyType": "string",
      "from": "foo",
      "to": "1234"
    },
    {
      "propertyName": "value_2",
      "currentPropertyType": "string",
      "from": "baz",
      "to": null
    }
  ]
}