POST {{receiver}}/api/v1/actions
Content-Type: application/json
Accept: application/json

{
    "targetExternalId": "9309213",
	"targetEntity": "article3",
	"targetService": "article-storage-3",
    "parentId": null,
	"actorExternalId": "9",
	"actorEntity": "promoter3",
	"actorService": "back-office-3",
    "name": "articlePublished",
    "emittedAt": "2006-01-02 15:04:05",
    "isAsync": false,
	"details": [
      {
        "propertyName": "status",
        "from": null,
        "to": "published"
      },
      {
        "propertyName": "value",
        "from": "bar",
        "to": "baz"
      }
	]
}

###

POST {{receiver}}/api/v1/actions
Content-Type: application/json
Accept: application/json

{
	"id": "34e1d82a-a065-436d-afd0-5fbcb752a4e1",
    "targetId": "122242120",
	"targetEntity": "subscription",
	"targetService": "billing",
    "crud": "update",
	"actorId": "88999",
	"actorEntity": "user",
	"actorService": "front",
    "eventName": "subscriptionUpdated",
    "emittedAt": 1578173212
}

###

POST {{receiver}}/api/v1/events
Content-Type: application/json
Accept: application/json

{
  "targetId": "111",
  "targetEntity": "post",
  "targetService": "post-service",
  "parentEventId": null,
  "actorId": "999",
  "crud": "create",
  "actorEntity": "blogger",
  "actorService": "blogger-hub",
  "eventName": "blogPostCreated",
  "emittedAt": 1578174655,
  "changes": [
    {
      "propertyName": "text",
      "currentPropertyType": "string",
      "from": null,
      "to": "foo says bar"
    },
    {
      "propertyName": "title",
      "currentPropertyType": "string",
      "from": null,
      "to": "baz title"
    },
    {
      "propertyName": "rating",
      "currentPropertyType": "float",
      "from": null,
      "to": 1.1
    },
    {
      "propertyName": "views",
      "currentPropertyType": "integer",
      "from": null,
      "to": 1
    }
  ]
}

###

POST {{receiver}}/api/v1/events
Content-Type: application/json
Accept: application/json

{
  "targetId": "111",
  "targetEntity": "post",
  "targetService": "post-service",
  "parentEventId": null,
  "actorId": "999",
  "crud": "delete",
  "actorEntity": "blogger",
  "actorService": "blogger-hub",
  "eventName": "blogPostDeleted",
  "emittedAt": 1578174657,
  "changes": [
    {
      "propertyName": "text",
      "from": "foo says bar",
      "to": null
    },
    {
      "propertyName": "title",
      "from": "baz title",
      "to": null
    },
    {
      "propertyName": "rating",
      "from": 1,
      "to": null
    }
  ]
}