// Code generated by MockGen. DO NOT EDIT.
// Source: model/microservice.go

// Package mock_model is a generated GoMock package.
package mock_model

import (
	model "github.com/denismitr/auditbase/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockMicroserviceRepository is a mock of MicroserviceRepository interface
type MockMicroserviceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMicroserviceRepositoryMockRecorder
}

// MockMicroserviceRepositoryMockRecorder is the mock recorder for MockMicroserviceRepository
type MockMicroserviceRepositoryMockRecorder struct {
	mock *MockMicroserviceRepository
}

// NewMockMicroserviceRepository creates a new mock instance
func NewMockMicroserviceRepository(ctrl *gomock.Controller) *MockMicroserviceRepository {
	mock := &MockMicroserviceRepository{ctrl: ctrl}
	mock.recorder = &MockMicroserviceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMicroserviceRepository) EXPECT() *MockMicroserviceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockMicroserviceRepository) Create(arg0 model.Microservice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockMicroserviceRepositoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMicroserviceRepository)(nil).Create), arg0)
}

// Delete mocks base method
func (m *MockMicroserviceRepository) Delete(ID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockMicroserviceRepositoryMockRecorder) Delete(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMicroserviceRepository)(nil).Delete), ID)
}

// Update mocks base method
func (m_2 *MockMicroserviceRepository) Update(ID string, m model.Microservice) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ID, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockMicroserviceRepositoryMockRecorder) Update(ID, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMicroserviceRepository)(nil).Update), ID, m)
}

// FirstByID mocks base method
func (m *MockMicroserviceRepository) FirstByID(ID model.ID) (model.Microservice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstByID", ID)
	ret0, _ := ret[0].(model.Microservice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstByID indicates an expected call of FirstByID
func (mr *MockMicroserviceRepositoryMockRecorder) FirstByID(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstByID", reflect.TypeOf((*MockMicroserviceRepository)(nil).FirstByID), ID)
}

// FirstByName mocks base method
func (m *MockMicroserviceRepository) FirstByName(name string) (model.Microservice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstByName", name)
	ret0, _ := ret[0].(model.Microservice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstByName indicates an expected call of FirstByName
func (mr *MockMicroserviceRepositoryMockRecorder) FirstByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstByName", reflect.TypeOf((*MockMicroserviceRepository)(nil).FirstByName), name)
}

// FirstOrCreateByName mocks base method
func (m *MockMicroserviceRepository) FirstOrCreateByName(name string) (model.Microservice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstOrCreateByName", name)
	ret0, _ := ret[0].(model.Microservice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstOrCreateByName indicates an expected call of FirstOrCreateByName
func (mr *MockMicroserviceRepositoryMockRecorder) FirstOrCreateByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstOrCreateByName", reflect.TypeOf((*MockMicroserviceRepository)(nil).FirstOrCreateByName), name)
}

// SelectAll mocks base method
func (m *MockMicroserviceRepository) SelectAll() ([]model.Microservice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAll")
	ret0, _ := ret[0].([]model.Microservice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAll indicates an expected call of SelectAll
func (mr *MockMicroserviceRepositoryMockRecorder) SelectAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAll", reflect.TypeOf((*MockMicroserviceRepository)(nil).SelectAll))
}
