// Code generated by MockGen. DO NOT EDIT.
// Source: persister/persister.go

// Package mock_persister is a generated GoMock package.
package mock_persister

import (
	gomock "github.com/golang/mock/gomock"
)
