// Code generated by MockGen. DO NOT EDIT.
// Package mock_utils is a generated GoMock package.
package mock_utils

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUUID4Generatgor is a mock of UUID4Generatgor interface
type MockUUID4Generatgor struct {
	ctrl     *gomock.Controller
	recorder *MockUUID4GeneratgorMockRecorder
}

// MockUUID4GeneratgorMockRecorder is the mock recorder for MockUUID4Generatgor
type MockUUID4GeneratgorMockRecorder struct {
	mock *MockUUID4Generatgor
}

// NewMockUUID4Generatgor creates a new mock instance
func NewMockUUID4Generatgor(ctrl *gomock.Controller) *MockUUID4Generatgor {
	mock := &MockUUID4Generatgor{ctrl: ctrl}
	mock.recorder = &MockUUID4GeneratgorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUUID4Generatgor) EXPECT() *MockUUID4GeneratgorMockRecorder {
	return m.recorder
}

// Generate mocks base method
func (m *MockUUID4Generatgor) Generate() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	return ret0
}

// Generate indicates an expected call of Generate
func (mr *MockUUID4GeneratgorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockUUID4Generatgor)(nil).Generate))
}
